### ISSUE TITLE
TODO scan traverses to root directory

### ISSUE THREAD

**Issue by acdha** [textmate/todo.tmbundle#4] opened 2011-03-22 15:56 UTC
Unless a file is currently selected, the TODO bundle will walk up to something like "../../../../../../../../../../../../../../../../../../../../../../../../…" and end up crawling the entire system disk after chewing 2-3 minutes of CPU.

**Comment by Soryu** [comment] 2011-03-26 18:06
The only case where this should be possible is when you create an adhoc project and drag some files in there that have no common base path, so the project directory would resolve to `/`. And in that case the current I get a warning that the command was aborted. “Warning: Your project directory is the root directory!”

Can you please check that you have the latest version of the bundle and if so, send me some steps on how to reproduce this? Thanks.

**Comment by acdha** [comment] 2011-03-26 19:08
I do have the latest version, receive no warnings and am using regular
projects. I'll investigate further and see if I can get a smaller
testcase.

Chris

On Mar 26, 2011, at 2:06 PM, Soryu
reply@reply.github.com
wrote:

**Comment by Soryu** [comment] 2011-03-26 21:53
OK. Btw, this is the source for the comment I’m talking about:

https://github.com/textmate/todo.tmbundle/blob/master/Support/todo.rb#L28

**Comment by jesseschutt** [comment] 2011-04-25 15:34
I'm seeing this similar behavior...

**Comment by sorbits** [comment] 2013-02-16 10:48
Can anyone provide a step-by-step for this issue?

Also, using TextMate 1.x or 2.0-alpha?

**Comment by sorbits** [comment] 2013-09-12 19:03
Closing due to lack of steps to reproduce.

**Closed as completed by sorbits** 2013-09-12 19:03 UTC
